swagger: '2.0'
info:
  version: '1.0.0'
  title: Cricket Score
  description: An API provide you results of a cricket match
  contact:
    name: Ryan Scott
    email: ryan@ryankscott.com
    url: http://www.ryankscott.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: apis.ryankscott.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /score/{id}:
    get:
      description: Returns a score based on a single ID
      operationId: findScoreById
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: id
          in: path
          description: ID of match to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: score response
          schema:
            $ref: '#/definitions/score'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  score:
    type: object
    required:
      - id
      - score
    properties:
      id:
        type: integer
        format: int64
      score:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
